version: '3.8'

services:

  insurance-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${INSURANCE_PORT}:${INSURANCE_PORT}"
    environment:
      - POSTGRES_DB_URL=${POSTGRES_DB_URL}
      - POSTGRES_DB_USERNAME=${POSTGRES_DB_USERNAME}
      - POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - CLIENT_SERVICE_URL=${CLIENT_SERVICE_URL}
      - INSURANCE_PORT=${INSURANCE_PORT}
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: client_insurance
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    ports:
      - "5432:5432"